spring:
  banner:
    image:
      location: banner.txt

#整合themleaf的相关配置
#开发时关闭缓存，不然没法看到实时页面
  thymeleaf:
    cache: false
    mode: HTML5
    #前缀
    #编码
    encoding: UTF-8
    #类型
    content-type: text/html
    #名称后缀
    suffix: .html

######数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/movie?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
#    可以自动识别
#    driver-class-name: com.mysql.jdbc.Driver
    #阿里巴巴数据源，如果不用则为默认的数据源
    type: com.alibaba.druid.pool.DruidDataSource

######redis的配置信息
  redis:
    database: 0  #redis的数据库个数是可以配置的，默认为16个，编号重0到15
    host: 47.114.190.175
    port: 6379
    timeout: 3000 #连接的超时时间，单位毫秒
    jedis:
      pool:
        max-idle: 200 #连接池中最大空闲连接，默认值为8。表示即使redis现在没有连接，也可以保持200个空闲的连接
        min-idle: 200 #连接池中的最小空闲连接，默认值是8
        max-active: 2000 #redis的最大连接数
        max-wait: -1

######控制台打印sql语句,一般用于本地的开发和测试
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl






#freemarker,本地一般设置为false,可以实时更新，生产建议为true
#  freemarker:
#    cache: false
#    charset: UTF-8
#    #指定HttpServletRequest的属性是否可以覆盖controller的model的同名项
#    allow-request-override: false
#    #检查模板位置是否存在。
#    check-template-location: true
##类型
#    content-type: text/html
#    #设置是否应该在与模板合并之前将所有请求属性添加到模型中。
#    expose-request-attributes: true
#    #设置是否在与模板合并之前将所有HttpSession属性添加到模型中
#    expose-session-attributes: true
#    #文件后缀名
#    suffix: .ftl
#    #路径
#    template-loader-path: classpath:/templates/




